In [1]:
import pandas as pd, numpy as np

df = pd.DataFrame({
    'patient_id': [101,102,103,101,104,105,102,106,107,107,108,108],
    'name':       ['Ravi','Anita','Kumar','Ravi','Divya','Suresh','Anita','Meena','Arun','arun ','Latha','Latha'],
    'age':        [45,32,50,45,28,60,32,41,38,38,np.nan,np.nan],
    'scan_date':  ['2026-01-05','2026-01-06','2026-01-07','2026-01-05','2026-01-08','2026-01-09',
                   '2026-02-10','2026-01-11','2026-01-12','2026-01-12','2026-01-13','2026-01-13'],
    'result':     ['Normal','Abnormal','Normal','Normal','Abnormal','Normal',
                   'Normal','Abnormal','Normal','Normal','Normal','Normal'],
})
df[df.duplicated()].index.to_list()

[3, 11]

In [2]:
df[df.duplicated(keep=False)].index.tolist()

[0, 3, 10, 11]

In [3]:
df.duplicated().tolist()
# True only at positions 3 and 11

[False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [4]:
df

    patient_id    name   age   scan_date    result
0          101    Ravi  45.0  2026-01-05    Normal
1          102   Anita  32.0  2026-01-06  Abnormal
2          103   Kumar  50.0  2026-01-07    Normal
3          101    Ravi  45.0  2026-01-05    Normal
4          104   Divya  28.0  2026-01-08  Abnormal
5          105  Suresh  60.0  2026-01-09    Normal
6          102   Anita  32.0  2026-02-10    Normal
7          106   Meena  41.0  2026-01-11  Abnormal
8          107    Arun  38.0  2026-01-12    Normal
9          107   arun   38.0  2026-01-12    Normal
10         108   Latha   NaN  2026-01-13    Normal
11         108   Latha   NaN  2026-01-13    Normal

In [5]:
df[df.duplicated(keep='last')]

    patient_id   name   age   scan_date  result
0          101   Ravi  45.0  2026-01-05  Normal
10         108  Latha   NaN  2026-01-13  Normal

In [6]:
df[df.duplicated(keep='first')]

    patient_id   name   age   scan_date  result
3          101   Ravi  45.0  2026-01-05  Normal
11         108  Latha   NaN  2026-01-13  Normal

In [7]:
df.drop_duplicates(keep='first')

    patient_id    name   age   scan_date    result
0          101    Ravi  45.0  2026-01-05    Normal
1          102   Anita  32.0  2026-01-06  Abnormal
2          103   Kumar  50.0  2026-01-07    Normal
4          104   Divya  28.0  2026-01-08  Abnormal
5          105  Suresh  60.0  2026-01-09    Normal
6          102   Anita  32.0  2026-02-10    Normal
7          106   Meena  41.0  2026-01-11  Abnormal
8          107    Arun  38.0  2026-01-12    Normal
9          107   arun   38.0  2026-01-12    Normal
10         108   Latha   NaN  2026-01-13    Normal

ONE HOT ENCODING

In [8]:
data=pd.read_csv(r'C:\Users\VP\Downloads\bank.csv')
text=['job','marital']
text.nunique()

AttributeError: 'list' object has no attribute 'nunique'

In [ ]:
text=data[['job','marital','education']].columns
data[text].nunique()
pd.get_dummies(data['job'],dtype=int)

job          12
marital       3
education     4
dtype: int64

In [ ]:
pd.get_dummies(data['job'],dtype=int)

,admin.,blue-collar,entrepreneur,housemaid,management,retired,self-employed,services,student,technician,unemployed,unknown
0,1,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
11157,0,1,0,0,0,0,0,0,0,0,0,0
11158,0,0,0,0,0,0,0,1,0,0,0,0
11159,0,0,0,0,0,0,0,0,0,1,0,0
11160,0,0,0,0,0,0,0,0,0,1,0,0
11161,0,0,0,0,0,0,0,0,0,1,0,0

Min-Max Scaling

In [ ]:
data[['age','balance',]].isna().sum()
scalar_learn=data[['age','balance',]]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mms=MinMaxScaler()

learnt=mms.fit(scalar_learn)
fill=mms.transform(scalar_learn)

Standardization:

In [ ]:
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()

scalar_done=ss.fit_transform(scalar_learn)

Robust Scaling

In [ ]:
from sklearn.preprocessing import RobustScaler
rs=RobustScaler()
rs.fit_transform(scalar_learn)

array([[ 1.17647059,  1.13051702],
       [ 1.        , -0.3184111 ],
       [ 0.11764706,  0.45397226],
       ...,
       [-0.41176471, -0.32849937],
       [ 0.23529412, -0.34678436],
       [-0.29411765, -0.34678436]], shape=(11162, 2))